on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.1'
          use-public-rspm: true
      
      # Install package from DESCRIPTION with remotes::install_local()
      - name: Install R Package
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_local(dependencies = TRUE)'

      # # If you want to use renv and a lockfile:
      # - name: Install R Dependencies
      #   uses: r-lib/actions/setup-renv@v2
      #   with:
      #     cache-version: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # - name: Install Python Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install polars

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}